### ISSUE TITLE
wrong hostname in documentation

### ISSUE THREAD

**Issue by armin-gardenanet** [tyler36/ddev-mailpit#16]
First of all thank you for your great addon!

In your documentation you mentioned mailpit as host, but for me it doesnt work. 
`MAIL_HOST=mailpit`

After changing it to localhost (with same port) it works.

**Comment by tyler36** [comment]
Thanks for the feedback. 
 
I'll make the change tomorrow ... unless you feel like submitting a PR?

**Comment by armin-gardenanet** [comment]
@tyler36 im not sure if im right. Actually im struggling with make it work. If im using localhost and port 1025 the emails are pointing to mailhog.
With mailpit as host, i'm getting an error "SMTP-Error: authentification failed". Do i have to provide username and password for mailpit? (in my SMTP config)

**Comment by tyler36** [comment]
I was doing some updates this morning and its working on Laravel.

I need more information.

What framework and version? Laravel 10? Drupal 9.5? 
How are you sending the mail? Via the UI or a command?

Please provide environment setup and steps I can follow to replicate the issue.

**Comment by armin-gardenanet** [comment]
I used PHPMailer 6.5 in our custom application.

```
$mail = new PHPMailer(true);
$mail->isSMTP();
$mail->Host = 'mailpit';
$mail->SMTPAuth = true;
$mail->Username = null;
$mail->Password = null;
$mail->SMTPSecure = false;
$mail->Port = 1025;
```

PHP version: 8.2
DDEV version: 1.21.6

**Comment by tyler36** [comment]
The service is currently run in a docker image with the host set as "mailpit", which I confirmed on a Laravel 10 and Drupal 10 install this morning.

Unfortunately, I have no experience with PHPMailer.
Your code above has SMTPAuth enabled and your error suggest that it's causing your issue.

I suggest you take a look at settings in the `./.ddev/mailpit/config.yaml`:

- https://github.com/axllent/mailpit/wiki
- https://github.com/axllent/mailpit/wiki/SMTP-with-STARTTLS-and-authentication

**Comment by tyler36** [comment]
I'm going to close this as the hostname is correct in the docs and functionality.

**Comment by armin-gardenanet** [comment]
I was able to find the problem. While using mailpit and PHPMailer, the follow line must be set to false (SMTPAuth must be disabled).
`$mail->SMTPAuth = false;`

Fun fact: i was migrating from mailhog to mailpit. With mailhog i could also use `$mail->SMTPAuth = true;` with empty credentials. Hope this help someone :)

Thank you @tyler36 for you great work!

**Comment by tyler36** [comment]
Glad you got it working @armin-gardenanet 

And thank you for the solution; it will save someone else a couple of hours googling in the future.
